import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/typography.css";

const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/sonner";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";

export const metadata: Metadata = {
  title: "ZulkifL Health Products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " overflow-x-hidden bg-brand-bg"}>
        {children}
        <Toaster />
      </body>
      <GoogleAnalytics gaId="G-MY5D34TB1Y" />
      <GoogleTagManager gtmId="AW-16643360312" />
    </html>
  );
}
